function [ D ] = drawDots( windowID , D , T , S , textIndexX , textIndexY  )
%DRAWDOTS Draw dots on the area defined by the current texture.
% Usage: [ D ] = drawDots( windowID , D , T , S , textIndexX , textIndexY  )
%
% Inputs:
%   : windowID - ID of the current window as returned by
%   Screen('OpenWindow')
%   : D - struct with dots-related parameters
%   : T - struct with textures
%   : S - struct containing very important info (screen, subject, colors,
%   trigger, response box, eyetracker, etc)
%   : textIndexX - texture index in X
%   : textIndexY - texture index in Y
%
% Output:
%   : D - struct with dots-related parameters (updated)
%

%% Pick template for dots
myTemplate = T.Template{textIndexY,textIndexX};

%% Exclude and draw

D.dots_in45 = [];
D.dots_in_45 = [];

for z=1:size(D.dots_xy45,1)
    if ( (myTemplate(min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),T.height),...
                   min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),T.height))==1 ...
            && ...
        myTemplate(max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),1),...
                   max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),1))==1 ...
            && ...
        myTemplate(max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),1),...
                   min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),T.height))==1 ...
            && ...
        myTemplate(min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),T.height),...
                   max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),1))==1 ) ...
            || ...
        (myTemplate(min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),T.height),...
                   min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),T.height))==3 ...
            && ...
        myTemplate(max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),1),...
                   max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),1))==3 ...
            && ...
        myTemplate(max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),1),...
                   min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),T.height))==3 ...
            && ...
        myTemplate(min(round(D.plaid_border45*D.dots_size45 + D.dots_xy45(z,2)),T.height),...
                   max(round(-D.plaid_border45*D.dots_size45 + D.dots_xy45(z,1)),1))==3 ) )
               
            D.dots_in45=[D.dots_in45,z];
            
    end
    
    if (myTemplate(min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),T.height), ...
                    min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),T.height))==2 ...
            && ...
        myTemplate(max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),1),...
                   max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),1))==2 ...
            && ...
        myTemplate(max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),1), ...
                   min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),T.height))==2 ...
            && ...
        myTemplate(min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),T.height),...
                   max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),1))==2 )
% %             || ...
% %         if ((myTemplate(min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),T.height), ...
% %                     min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),T.height))==3 ...
% %             && ...
% %         myTemplate(max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),1),...
% %                    max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),1))==3 ...
% %             && ...
% %         myTemplate(max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),1), ...
% %                    min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),T.height))==3 ...
% %             && ...
% %         myTemplate(min(round(D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,2)),T.height),...
% %                    max(round(-D.plaid_border_45*D.dots_size_45 + D.dots_xy_45(z,1)),1))==3  ) )
                
            D.dots_in_45=[D.dots_in_45,z];
            
    end
end

Screen('DrawDots', windowID, [S.screenX/2-T.height/2+D.dots_xy45(D.dots_in45,1)';S.screenY/2-T.height/2+D.dots_xy45(D.dots_in45,2)'] , D.dots_size45 , D.dotsColor , [] , 0 );
Screen('DrawDots', windowID, [S.screenX/2-T.height/2+D.dots_xy_45(D.dots_in_45,1)';S.screenY/2-T.height/2+D.dots_xy_45(D.dots_in_45,2)'] , D.dots_size_45 , D.dotsColor , [] , 0 );

end %End function